[project]
name = "employee-management-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shawn Mathias", email = "shawn7797@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.18.1",
]

[project.scripts]
employee-management-django = "employee_management_django:main"

[tool.vercel]
entrypoint = "core.wsgi:application"
